@echo off
echo STARTING BACKEND...
start /B uv run uvicorn src.main:app --host 127.0.0.1 --port 8000 > server.log 2>&1
echo Waiting for server to start...
timeout /t 5

echo RUNNING E2E TESTS...
uv run pytest e2e/ --headed --slowmo 300

echo STOPPING SERVER...
taskkill /IM uvicorn.exe /F
pause
