@echo off
echo ЗАПУСК BACKEND...
start /B uv run uvicorn src.main:app --host 127.0.0.1 --port 8000 > server.log 2>&1
echo Ожидание запуска сервера...
timeout /t 5

echo ЗАПУСК E2E ТЕСТОВ...
uv run pytest e2e/ --headed --slowmo 300

echo ОСТАНОВКА СЕРВЕРА...
taskkill /IM uvicorn.exe /F
pause
